project_id = "vvtympzatclvjaqucebr"

[functions.organograma-svg]
verify_jwt = false

[functions.organograma-png]
verify_jwt = false

[functions.enviar-relatorio-km-pendentes]
verify_jwt = false

[functions.notificar-novo-cadastro]
verify_jwt = false
