// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});

// As tabelas do RH foram movidas para o schema dedicado `rh` (nomes seguem `rh_*`).
// Use `rhDb` para TODA leitura/escrita de tabela rh_* (rhDb.from("rh_...")).
// ⚠️ As RPCs continuam no schema `public` — chame com supabase.rpc("rh_..."), sem .schema.
//
// Runtime: recebe a string "rh" → consultas vão para o schema `rh` (Accept/Content-Profile: rh).
// Tipos: o gerador do Supabase emite os shapes das tabelas rh_* dentro de `public`,
// então tipamos o argumento como "public" (só em tempo de compilação) para o rhDb.from()
// manter o autocompletar/checagem de colunas e os selects aninhados (relations).
export const rhDb = supabase.schema("rh" as unknown as "public");